spring.application.name=ms-tecnologia
server.port=8080

# R2DBC MySQL
spring.r2dbc.url=r2dbc:mysql://localhost:3307/db_tecnologia
spring.r2dbc.username=root
spring.r2dbc.password=root

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
